name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16] # Test with multiple Node.js versions

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Check for Azure connection (informational)
        run: |
          echo "** Checking for Azure connection (informational only) **"
          # (Optional) Enumerate environment variables or Azure CLI commands
          # to provide more details about a potential Azure connection
          echo "  - Environment variables (for informational purposes only):"
          env | grep -E '^AZURE|^ARM_'  # Filter for potential Azure-related variables
          echo "  - Azure CLI availability (if installed):"
          az --version  # Check for Azure CLI if available (informational only)

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Copy files via SSH
        uses: appleboy/scp-action@master # Consider security implications of using secrets
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "/home/azureuser/nodeproject/server"

      - name: Execute commands on the server
        uses: appleboy/ssh-action@master # Consider security implications of using secrets
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/azureuser/nodeproject/server
            npm install
            npm run start
