name: "Ohmywall_Backend"

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13

      - name: Build
        run: |
          go build -o main
          echo "Build completed successfully!"  # Debug message after build

      - name: Test
        run: |
          go test ./...
          echo "Tests passed!"  # Debug message after tests

      - name: Login to Azure using Managed Identity (recommended)
        uses: azure/login@v1
        with: # Keep this for Managed Identity
          useDeviceAuth: true # Only necessary for interactive logins
