name: Ohmywall_Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        # Debug: Verify repository checkout
        run: |
          echo "Successfully checked out repository!"

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13
        # Debug: Verify Go version setup
        run: |
          echo "Go version $(go version) is set up."

      - name: Build
        run: |
          go build -o main
          echo "Build completed successfully!"
        # Debug: Capture specific build output (optional)
        # run: |
        #   go build -o main 2>&1 | tee build_output.log

      - name: Test
        run: |
          go test ./...
          echo "Tests passed!"
        # Debug: Capture specific test output (optional)
        # run: |
        #   go test ./... -v 2>&1 | tee test_output.log

      - name: Upload Build Artifact to Azure VM using OpenSSH
        run: |
          echo "Connecting to Azure VM..."
          scp -o StrictHostKeyChecking=no ./main azureuser@<your_vm_ip_address>:/path/to/destination/directory/on/VM
          echo "Upload to VM complete!"

          # (Optional) Additional security measure: Remove the known_hosts entry after upload
          ssh-keygen -R <your_vm_ip_address>
