env:
  OUTPUT_PATH: ${{ github.workspace }}
  GOLANG_CODE_PATH: /path/to/your/golang/code/directory

on: [push]

jobs:
  # Upload Golang code to VM
  UploadCode:
    runs-on: ubuntu-latest # Use Ubuntu for SCP transfer

    steps:
      - name: Checkout code from repo
        uses: actions/checkout@v1

      - name: Install SSH dependencies
        run: |
          sudo apt update
          sudo apt install openssh-client

      - name: Get VM details from workflow (optional)
        # Assuming VM details are stored in secrets or environment variables
        # Replace with actual variable names if applicable
        env:
          VM_IP_ADDRESS: ${{ secrets.VM_IP_ADDRESS }}
          VM_USERNAME: ${{ secrets.VM_USERNAME }}
        # Comment out the below step if using hardcoded values
        # run: echo "VM_IP_ADDRESS=${{ secrets.VM_IP_ADDRESS }}, VM_USERNAME=${{ secrets.VM_USERNAME }}"

      - name: Upload Golang code to VM
        # Replace with retrieved or hardcoded VM details
        env:
          VM_IP_ADDRESS: your_vm_ip_address # Replace with actual IP if not retrieved
          VM_USERNAME: your_vm_username # Replace with actual username if not retrieved
        run: |
          scp -r ${{ env.OUTPUT_PATH }}/${{ env.GOLANG_CODE_PATH }} ${VM_USERNAME}@${VM_IP_ADDRESS}:/home/azureuser/project/main
