name: "Ohmywall_Backend"

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13

      - name: Build
        run: go build -o main

      - name: Test
        run: go test ./...

      - name: Login to Azure using Managed Identity (recommended)
        uses: azure/login@v1
        with:
          useDeviceAuth: true # Enables Managed Identity for Azure Resources

      - name: Upload Build Artifacts to Azure Storage (optional)
        uses: actions/upload-artifact@v2
        with:
          name: ohmywall-backend-artifacts
          path: ./main

      - name: Deploy to Azure VM using Azure Remote Commands (ARM)
        run: |
          az vm run-command invoke \
            --resource-group go_server \
            --name goserver \
            --command-id RunPowershellScript \
            --scripts | tee /dev/null

          # Example PowerShell script for deployment within the VM (replace with your actual commands)
          Write-Host "Downloading build artifacts..."
          # Download artifacts from Azure Storage if uploaded (replace with download URI)
          # Download-File https://your-storage-account.blob.core.windows.net/ohmywall-backend-artifacts/main -Destination /home/azureuser/project/main

          Write-Host "Stopping your-backend-service..."
          # Replace with the actual command to stop your service

          Write-Host "Replacing application with new build..."
          cp /path/to/downloaded/artifact /home/azureuser/project/main

          Write-Host "Starting your-backend-service..."
          # Replace with the actual command to start your service

          Write-Host "Deployment complete!"
