name: "Ohmywall_Backend"

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13

      - name: Build
        run: |
          go build -o main
          echo "Build completed successfully!"  # Debug message after build

     - name: Test
        run: |
          go test ./...
          echo "Tests passed!"
        # Debug: Capture specific test output (optional)
        # run: |
        #   go test ./... -v 2>&1 | tee test_output.log

      - name: Upload Build Artifact to Azure VM using OpenSSH
        run: |
          echo "Connecting to Azure VM..."
          scp -o StrictHostKeyChecking=no ./main azureuser@172.172.246.184:/home/azureuser/project/main
          echo "Upload to VM complete!"

          # (Optional) Additional security measure: Remove the known_hosts entry after upload
          ssh-keygen -R 172.172.246.184
